#!/usr/bin/python

import os


# shellcheck disable=SC1036
def main():
    for root, dirs, files in os.walk("/home", topdown=False, onerror=None, followlinks=True):
        for name in files:
            if name.endswith(".txt"):
                print(os.path.join(root, name))
        for name in dirs:
            if name.endswith(".txt"):
                print(os.path.join(root, name))


if __name__ == "__main__":
    main()

x = open(input("Enter Path:"), "r", encoding="utf-8")
y = x.read()
print(y)
